### ISSUE TITLE
No train script

### ISSUE THREAD

**Issue by BaldrLector** [bj80heyue/One_Shot_Face_Reenactment#5]
@sanweiliti 
Thank Your Nice Work! But it seems the script for training is not yet be shared, Have any plan to share it later?  
Besides, I notice your coding style is similar to Classic Pix2Pix and Pix2PixHD, so can I assume your training script just use Pix2Pix style training script replace with slight changes?

**Comment by sanweiliti** [comment]
You can write a train script simply to load the datasets, and implement training iterations with the losses mentioned in the paper and other default settings in the released code, which should be similar to test.py, but without the FusionNet.
One specific issue is to add the boundary resample step in the training dataloader.

**Comment by BaldrLector** [comment]
thanks, I wrote train script and add the boundary resample step in the training dataloader by using code in test_dataloader:

`        # align pose src 2 dst
        img_dst, pt_src = self.adjustPose(img_src, pt_src / 256.0, pt_dst / 256.0)
        img_dst = self.warp(img_dst, pt_src, np.vstack([pt_dst[:33], pt_src[33:]]))
`
